global:
  hidden_dim: 128

ACM:
  MyMLP:
    rank: 2
    tanh: True
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.5
    regularization_weight: 0.1
  MLP:
    learning_rate: 0.01
    weight_decay: 0.005
    dropout_ratio: 0.5
  RSAGE:
    learning_rate: 0.01
    weight_decay: 0.0005
    dropout_ratio: 0.5
  RGCN:
    learning_rate: 0.01
    weight_decay: 0.001
    dropout_ratio: 0.5
  RGAT:
    learning_rate: 0.01
    weight_decay: 0.0005
    num_heads: 8
    dropout_ratio: 0.6
    attn_dropout_ratio: 0.3
  HAN:
    learning_rate: 0.01
    weight_decay: 0.001
    num_heads: 8
    dropout_ratio: 0.6
    attn_dropout_ratio: 0.3

IMDB:
  MyMLP:
    rank: 1
    tanh: True
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.5
    regularization_weight: 0.1
  MLP:
    learning_rate: 0.01
    weight_decay: 0.005
    dropout_ratio: 0.5
  RSAGE:
    learning_rate: 0.01
    weight_decay: 0.0005
    dropout_ratio: 0.5
  RGCN:
    learning_rate: 0.01
    weight_decay: 0.0001
    dropout_ratio: 0.5
  RGAT:
    learning_rate: 0.01
    weight_decay: 0.0005
    num_heads: 8
    dropout_ratio: 0.6
    attn_dropout_ratio: 0.3
  HAN:
    learning_rate: 0.01
    weight_decay: 0.0001
    num_heads: 8
    dropout_ratio: 0.6
    attn_dropout_ratio: 0.3

IMDB5K:
  MyMLP:
    rank: 1
    tanh: True
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.5
    regularization_weight: 0.1
  MLP:
    learning_rate: 0.01
    weight_decay: 0.005
    dropout_ratio: 0.5
  RSAGE:
    learning_rate: 0.01
    weight_decay: 0.0005
    dropout_ratio: 0.5

DBLP:
  MyMLP:
    rank: 3
    tanh: True
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.5
    regularization_weight: 0.001
  MLP:
    learning_rate: 0.01
    weight_decay: 0.005
    dropout_ratio: 0.5
  RSAGE:
    learning_rate: 0.01
    weight_decay: 0.0005
    dropout_ratio: 0.5

ArXiv:
  MyMLP:
    rank: 1
    tanh: True
    hidden_dim: 1024
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.
    norm_type: batch
    regularization_weight: 0.001
  MLP:
    hidden_dim: 1024
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.
    norm_type: batch
  RSAGE:
    learning_rate: 0.01
    weight_decay: 0.0
    dropout_ratio: 0.5
  RGCN:
    learning_rate: 0.01
    weight_decay: 0.0
    dropout_ratio: 0.5
  RGAT:
    learning_rate: 0.01
    weight_decay: 0.0
    num_heads: 8
    dropout_ratio: 0.6
    attn_dropout_ratio: 0.3
  HAN:
    learning_rate: 0.01
    weight_decay: 0.0
    num_heads: 8
    dropout_ratio: 0.6
    attn_dropout_ratio: 0.3

MAG:
  MyMLP:
    rank: 2
    tanh: True
    hidden_dim: 1024
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.
    norm_type: batch
    regularization_weight: 0.01
  MGFNN:
    hidden_dim: 1024
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.
    norm_type: batch
  MLP:
    hidden_dim: 1024
    learning_rate: 0.01
    weight_decay: 0.00
    dropout_ratio: 0.5
    norm_type: batch
  RSAGE:
    hidden_dim: 128
    learning_rate: 0.01
    weight_decay: 0.0
    dropout_ratio: 0.5
